"use client";
import { Providers } from './providers'
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from '../components/main/NavBar';
import { AuthContextProvider, UserAuth } from "./context/AuthContext";
import { useRouter } from 'next/navigation';
import { useState, useEffect } from 'react';

const inter = Inter({ subsets: ["latin"] });


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// Exclude NavBar from the login page

export default function RootLayout({ children }) {
  const router = useRouter();
  const [excludeNavBar, setExcludeNavBar] = useState(false);

  useEffect(() => {
    // Check the pathname after the initial rendering
    setExcludeNavBar(router.pathname === '/login');
  }, [router.pathname]);
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthContextProvider>
            {!excludeNavBar && <NavBar />}
            {children}
          </AuthContextProvider>
        </Providers>
      </body>
    </html>
  );
}
