const regionMap = {
  1: "Central",
  2: "Central",
  3: "Central",
  4: "Central",
  5: "Central",
  6: "Central",
  7: "Central",
  8: "Central",
  9: "Central",
  10: "Central",
  11: "Central",
  12: "Central",
  13: "Central",
  14: "Central",
  15: "Central",
  21: "Central",
  16: "East",
  17: "East",
  18: "East",
  19: "North-East",
  20: "North-East",
  28: "North-East",
  22: "West",
  23: "West",
  24: "West",
  25: "North",
  26: "North",
  27: "North",
};

export default regionMap;
